defaultLanguageName: 'node'
defaultSemverRangePrefix: ''
enableColors: true
enableImmutableCache: true
enableImmutableInstalls: true
enableProgressBars: true
enableStrictSsl: true
enableTimers: true
lockfileFilename: 'yarn.lock'
progressBarStyle: 'simba'
